### ISSUE TITLE
Dose the network use depth pre-training?

### ISSUE THREAD

**Issue by Cc-Hy** [amazon-research/progressive-coordinate-transforms#11]
Hello, good job!
I'd like to know if the network is pre-trained on a depth dataset?
Thanks.

**Comment by Willy0919** [comment]
> Hello, good job! I'd like to know if the network is pre-trained on a depth dataset? Thanks.

For KITTI dataset, we use the pre-trained depth estimator DORN as in other methods, which is pre-trained on the KITTI depth dataset. For Waymo dataset, we pre-train the depth estimator based on the sparse depth map generated by corresponding point clouds.

**Comment by Cc-Hy** [comment]
Thanks a lot.
