### ISSUE TITLE
How much time does it take to convert Waymo to KITTI format?

### ISSUE THREAD

**Issue by abhi1kumar** [amazon-research/progressive-coordinate-transforms#16]
Thank you for amazing work. I wanted to know how much time does it take to convert Waymo to KITTI format using the script

```bash
python converter.py --save_dir datasets/waymo_open_organized/ --split validation
```

The validation one seems to take a lot of time on my machine, and so wanted to confirm.

**Comment by Willy0919** [comment]
Yes, it will take a lot of time to convert Waymo dataset to KITTI format, and the numer of processes you set (argument --num_proc) also influences the convert time.

**Comment by abhi1kumar** [comment]
@Willy0919 Thankyou for your response. It was taking a lot of time, and this made me think that I might be doing wrong on my end. Your answer confirms that I am doing it correctly on my end.
