### ISSUE TITLE
How May I get the staff in data/KITTI/pickle_files/org?

### ISSUE THREAD

**Issue by YunzheWu-404** [amazon-research/progressive-coordinate-transforms#6]
Hi,
Thank you very much for sharing your great work.
I would like to ask how may I get the 2d image features needed in data/KITTI/pickle_files/org?

Best

**Comment by Willy0919** [comment]
You can first use pretrained 2D detector to generate and save intermediate features, then use tools/data_prepare/patch_data_prepare_val.py to generate your own pickle files on saved features.

**Comment by rockywind** [comment]
Hi, 
Thank you very much for sharing your great work.
How to generate intermediate features from pre-trained 2d detection.
`[Errno 2] No such file or directory: '../../data/KITTI/pickle_files/org/000000.pickle'`

**Comment by YunzheWu-404** [comment]
Thanks, I will give a try.
