### ISSUE TITLE
About generating 2D detection feature!

### ISSUE THREAD

**Issue by rockywind** [amazon-research/progressive-coordinate-transforms#9]
Hi, thanks for sharing your great work!
Do you share your 2D detection feature file?
Or could you tell me which layer's feature should be saving in RTM3D?
> you need to generate image 2D features for the 2D bounding boxes and put them to data/KITTI/pickle_files/org

**Comment by Willy0919** [comment]
We select the features from last layer of 2D detector in our experiments, but you can adapt the most suitable features in your experiments.

**Comment by rockywind** [comment]
Thanks a lot!
